---
title: "On the blog"
---

## r-blog-en {#r-blog-en}

- [2024-06-14] — [webrcli & spidyr: What's new](/posts/webrcli-and-spidyr-whats-new.html)
- [2024-03-06] — [webrcli & spidyr: A starter pack for building NodeJS projects with webR inside](/posts/webrcli-and-spidyr.html)
- [2023-11-21] — [Rethinking packages & functions preloading in webR 0.2.2](/posts/rethinking-packages-and-functions-preloading-in-webr-0.2.2.html)
- [2023-10-17] — [Using my own R functions in webR in an Express JS API, and thoughts on building web apps with Node & webR](/posts/using-own-functions-in-webr-node-js.html)
- [2023-09-04] — [Preloading your R packages in webR in an Express JS API](/posts/preloading-your-r-packages-in-webr-in-an-express-js-api.html)
- [2023-07-25] — [The Old Faithful Geyser Data shiny app with webR, Bootstrap & ExpressJS](/posts/old-faithful-express-bootstrap-webr.html)
- [2023-07-04] — [Using webR in an Express JS REST API](/posts/calling-webr-from-expressjs.html)
- [2023-05-05] — [\[Keynote\] Production is like ultra running: brutal, ungrateful, but worth every step](/posts/keynote-shiny-conf-2023.html)
- [2021-12-02] — [Advent of Code 2021-02 with R & JavaScript](/posts/aoc-2021-02.html)
- [2021-12-01] — [Advent of Code 2021-01 with R & JavaScript](/posts/aoc-2021-01.html)
- [2021-10-04] — [The 'Engineering Production-Grade Shiny Apps' book is available in print!](/posts/engineering-shiny-print.html)
- [2021-02-28] — [Add POST requests to {shiny} with {brochure}](/posts/post-request-shiny-app-brochure.html)
- [2021-02-18] — [Multi-page {shiny} Applications with {brochure}](/posts/brochure-r-package.html)
- [2020-12-09] — [Advent of Code 2020-09 with R](/posts/aoc-2020-09.html)
- [2020-12-08] — [Advent of Code 2020-08 with R](/posts/aoc-2020-08.html)
- [2020-12-07] — [Advent of Code 2020-07 with R & Neo4j](/posts/aoc-2020-07.html)
- [2020-12-06] — [Advent of Code 2020-06 with R](/posts/aoc-2020-06.html)
- [2020-12-05] — [Advent of Code 2020-05 with R](/posts/aoc-2020-05.html)
- [2020-12-04] — [Advent of Code 2020-04 with R](/posts/aoc-2020-04.html)
- [2020-12-03] — [Advent of Code 2020-03 with R](/posts/aoc-2020-03.html)
- [2020-12-02] — [Advent of Code 2020-02 with R & JavaScript](/posts/aoc-2020-02.html)
- [2020-12-01] — [Advent of Code 2020-01 with R & JavaScript](/posts/aoc-2020-01.html)
- [2020-10-05] — [We Run for RLadies](/posts/we-run-rladies.html)
- [2020-09-20] — ['Run for RLadies' online event](/posts/run-rladies.html)
- [2020-07-28] — [Can I host my R packages on npm? (Spoiler: yes)](/posts/r-package-npm.html)
- [2020-07-15] — [{hexmake} is one of the 5 Grand Prizes of the 2020 Shiny Contest](/posts/hexmake-shiny-contest.html)
- [2020-07-13] — [clientsdb - A docker image with clients comments](/posts/clients-db.html)
- [2020-06-17] — [Hello hordes!](/posts/hello-hordes.html)
- [2020-05-31] — [Learning Shiny for Production](/posts/learn-shiny-production.html)
- [2020-05-11] — [Fetch API Results from the Browser and send them to Shiny](/posts/api-from-client-shiny.html)
- [2020-05-07] — [How to Write an R Package Wrapping a NodeJS Module](/posts/node-r-package.html)
- [2020-04-20] — [Use R & GitHub as a Workout planner](/posts/r-git-workout-planner.html)
- [2020-03-12] — [Automate the Creation of an API Wrapper package by Scraping its Online Documentation](/posts/fun-from-api-doc.html)
- [2020-01-08] — [How to use your Garmin watch to tell your team you're going for a run](/posts/api-call-garmin-watch.html)
- [2020-01-05] — [chuck — A training tool for deploying Shiny Apps](/posts/chuck-deployment-shiny-docker-kubernetes.html)
- [2019-12-08] — [Advent of Code 2019-08 with R & JavaScript](/posts/aoc-2019-08.html)
- [2019-12-07] — [Advent of Code 2019-07 with R](/posts/aoc-2019-07.html)
- [2019-12-06] — [Advent of Code 2019-06 with R ](/posts/aoc-2019-06.html)
- [2019-12-05] — [Advent of Code 2019-05 with R & JavaScript](/posts/aoc-2019-05.html)
- [2019-12-04] — [Advent of Code 2019-04 with R & JavaScript](/posts/aoc-2019-04.html)
- [2019-12-03] — [Advent of Code 2019-03 with R & JavaScript](/posts/aoc-2019-03.html)
- [2019-12-02] — [Advent of Code 2019-02 with R & JavaScript](/posts/aoc-2019-02.html)
- [2019-12-01] — [Advent of Code 2019-01 with R & JavaScript](/posts/aoc-2019-01.html)
- [2019-09-23] — [JavaScript const in R](/posts/js-const-r.html)
- [2019-09-06] — [One week as a Shiny dev, seen through Google search](/posts/one-week-shiny-google-search.html)
- [2019-07-14] — [Back from useR! 2019](/posts/back-from-toulouse.html)
- [2019-05-22] — [Create a CLI for R with npm](/posts/create-r-cli-npm.html)
- [2019-04-15] — [{attempt} 0.3.0 is now on CRAN](/posts/attempt-0-3-0.html)
- [2019-03-31] — [See you at useR! Toulouse](/posts/see-you-user-2019.html)
- [2019-01-29] — [Watch if R is running from Shiny](/posts/watch-r-shiny.html)
- [2019-01-06] — [An Introduction to Docker for R Users](/posts/docker-r-reproducibility.html)
- [2019-01-02] — [2018 through {cranlogs}](/posts/12-months-cranlogs.html)
- [2018-12-04] — [Solving #AdventOfCode day 3 and 4 with R](/posts/advent-code-3-4.html)
- [2018-12-04] — [Solving #AdventOfCode day 5 and 6 with R](/posts/advent-code-5-6.html)
- [2018-12-02] — [Solving #AdventOfCode day 1 and 2 with R](/posts/advent-code-1-2.html)
- [2018-09-24] — [Why do we use arrow as an assignment operator?](/posts/r-assignment.html)
- [2018-08-06] — [Wrangling Wikileaks DMs](/posts/wikileaks.html)
- [2018-07-30] — [About lazy evaluation](/posts/lazyeval.html)
- [2018-07-17] — [A quick #WorldEmojiDay exploration](/posts/worldemojiday.html)
- [2018-07-14] — [\[Web2Day\] Producing web content with R](/posts/web-dev-r.html)
- [2018-07-07] — [Happy dev with {purrr}](/posts/happy-dev-purrr.html)
- [2018-05-28] — [Serve your dataset in RStudio Connection Pane with {fryingpane}](/posts/frying-pane.html)
- [2018-04-22] — [Playing with #rstatsnyc, Neo4J and R](/posts/rstatsnyc-neo4j.html)
- [2018-04-18] — [\[How to\] Write a purrr-like adverb](/posts/purrr-adverb-tidyverse.html)
- [2018-03-02] — [dockerfiler is now on CRAN](/posts/dockerfiler-cran.html)
- [2018-02-15] — [Explain R environments like I’m five](/posts/explain-environments-eli5.html)
- [2018-01-21] — [Can (a==1 & a==2 & a==3) ever evaluate to TRUE?](/posts/active-binding-r-enigma.html)
- [2018-01-21] — [\[How to\] Build an API wrapper package in 10 minutes.](/posts/build-api-wrapper-package-r.html)
- [2018-01-16] — [Combining the new {rtweet} and {tidytext}](/posts/rtweet-tidytext.html)
- [2018-01-12] — [\[How to\] Include a dancing banana in your R package documentation](/posts/dancing-banana-r-package-doc.html)
- [2018-01-09] — [Some random R benchmarks](/posts/random-r-benchmarks.html)
- [2018-01-03] — [{attempt} is now on CRAN](/posts/attempt-cran.html)
- [2017-12-28] — [A Crazy Little Thing Called {purrr} - Part 6 : doing statistics](/posts/purrr-statistics.html)
- [2017-12-20] — [A Crazy Little Thing Called {purrr} - Part 5: code optimization](/posts/purrr-code-optim.html)
- [2017-12-12] — [A Crazy Little Thing Called {purrr} - Part 4: mappers](/posts/purrr-mappers.html)
- [2017-12-06] — [A Crazy Little Thing Called {purrr} - Part 3 : Setting NA](/posts/purrr-set-na.html)
- [2017-11-29] — [A Crazy Little Thing Called {purrr} - Part 2 : Text Wrangling](/posts/purrr-text-wrangling.html)
- [2017-11-24] — [A Crazy Little Thing Called {purrr} - Part 1 : Web Mining ](/posts/purrr-web-mining.html)
- [2017-11-17] — [Back from Budapest](/posts/back-budapest.html)
- [2017-11-09] — [Budapest Here I Come](/posts/coming-budapest.html)
- [2017-11-01] — [Collecting tweets with R and {rtweet}](/posts/collect-rtweet.html)
- [2017-09-27] — [{proustr} 0.2.0 is on CRAN](/posts/proustr-0-2-0.html)
- [2017-09-11] — [\[New Package\] {tidystringdist}](/posts/tidystringdist.html)
- [2017-08-29] — [R6 and parent exposure](/posts/r6-parent-exposure.html)
- [2017-08-23] — [Why Can't I Remember Game of Thrones Characters? An Analysis in R](/posts/game-of-thrones-characters-r.html)
- [2017-08-15] — [R6 and shared objects](/posts/r6-shared-objects.html)
- [2017-08-12] — [R and active binding (and pizza)](/posts/ractivebinfing.html)
- [2017-07-19] — [languagelayeR 1.1.0 is now on CRAN](/posts/languagelayer110.html)
- [2017-07-14] — [Down the rabbit hole with tidy eval — Part 1](/posts/tidyeval-1.html)
- [2017-07-09] — [Back from useR!2017: a summer to-do list](/posts/back-user2017.html)
- [2017-06-29] — [Playing with R, infix functions, and pizza](/posts/playing-r-infix-functions.html)
- [2017-06-05] — [New R Package — proustr](/posts/proustr-package.html)
- [2017-05-31] — [\[Just for fun\] New R package — tuRbonegro](/posts/rstats-turbonegro.html)
- [2017-05-09] — [Mapping the French second round results with R](/posts/mapping-the-french-second-round-results-with-r.html)
- [2017-04-28] — [Predict french vote with R](/posts/predict-french-vote-with-r.html)
- [2017-04-13] — [#RStats — Create a pixel map with R"](/posts/rstats-create-a-pixel-map-with-r.html)
- [2017-04-02] — [Playing with #RStats and Microsoft Computer Vision API](/posts/playing-with-rstats-and-microsoft-computer-vision-api.html)
- [2017-03-26] — [#RStats — API calls and Sys.sleep](/posts/rstats-api-calls-and-sys-sleep.html)
- [2017-03-15] — [1 dataset, 10 visualisations with R](/posts/1-dataset-10-dataviz-with-r.html)
- [2017-03-01] — [Create an heatmap with R and ggplot2](/posts/create-an-heatmap-with-r-and-ggplot2.html)
- [2016-12-23] — [All I want for Christmas is a #Dataviz](/posts/all-i-want-for-christmas-is-a-dataviz-2.html)
- [2016-12-12] — [#RStats — languagelayeR : query the languagelayer API with R](/posts/rstats-languagelayer-query-the-languagelayer-api-with-r.html)
- [2016-08-31] — [Data & Vinyls — A discogs library exploration with R](/posts/data-vinyles-discogs-r.html)
- [2016-08-17] — [rpinterest now on CRAN](/posts/rpinterest-cran.html)
- [2016-07-30] — [rpinterest : acess the Pinterest API with R](/posts/rpinterest-package-r.html)
- [2016-07-28] — [Create a map with R — rgeoapi, ggmap and ggplot2](/posts/create-map-ggplot2-rgeoapi-ggmap.html)
- [2016-06-05] — [rgeoapi — A package to access the GéoAPI](/posts/rgeoapi-package-r.html)
- [2016-05-24] — [#RStats — Text mining with R and gutenbergr](/posts/rstats-text-mining-r-gutenbergr-2.html)

## r-blog-fr {#r-blog-fr}

- [2017-05-10] — [#RStats et Microsoft Computer Vision](/posts/rstats-microsoft-computer-vision-api-2.html)
- [2017-05-08] — [Cartographier le second tour français avec R](/posts/cartographier-second-tour-francais-r.html)
- [2017-04-14] — [#RStats — API calls et Sys.sleep](/posts/rstats-api-calls-sys-sleep.html)
- [2017-03-19] — [Une heatmap avec R et ggplot2](/posts/heatmap-avec-r-et-ggplot2.html)
- [2017-03-12] — [1 dataset, 10 visualisations — retour de La Fabrique de l’info](/posts/1-dataset-10-visualisations.html)
- [2016-12-23] — [All I want for Christmas is a #Dataviz](/posts/all-i-want-for-christmas-is-a-dataviz.html)
- [2016-12-20] — [languagelayeR 1.0.0 disponible sur le CRAN](/posts/languagelayer-1-0-0-disponible-cran.html)
- [2016-12-12] — [#RStats — languagelayeR : accéder à l'API languagelayer avec R](/posts/rstats-languagelayer-api.html)
- [2016-10-31] — [rgeoapi 1.1.0 disponible sur le CRAN !](/posts/rgeoapi-1-1-0-disponible-cran.html)
- [2016-08-31] — [Data & Vinyles — Exploration d'une bibliothèque Discogs avec R](/posts/data-vinyles-bibliotheque-discogs-r.html)
- [2016-08-17] — [rpinterest disponible sur le CRAN](/posts/rpinterest-disponible-cran.html)
- [2016-07-30] — [rpinterest : un package R pour accéder à l'API Pinterest](/posts/rpinterest-un-package-r-pour-acceder-a-lapi-pinterest.html)
- [2016-07-28] — [Créer une carte avec R — rgeoapi et ggplot2](/posts/carte-r-rgeoapi-ggplot2.html)
- [2016-07-20] — [Mise à jour du package R : rgeoapi](/posts/rgeoapi-v1.html)
- [2016-06-05] — [rgeoapi — Un package R pour accéder à la GéoAPI](/posts/rgeoapi.html)
- [2016-05-24] — [#RStats — Text mining avec R et gutenbergr](/posts/rstats-text-mining-r-gutenbergr.html)

## webr {#webr}

- [2024-06-14] — [webrcli & spidyr: What's new](/posts/webrcli-and-spidyr-whats-new.html)
- [2024-03-06] — [webrcli & spidyr: A starter pack for building NodeJS projects with webR inside](/posts/webrcli-and-spidyr.html)
- [2023-11-21] — [Rethinking packages & functions preloading in webR 0.2.2](/posts/rethinking-packages-and-functions-preloading-in-webr-0.2.2.html)
- [2023-10-17] — [Using my own R functions in webR in an Express JS API, and thoughts on building web apps with Node & webR](/posts/using-own-functions-in-webr-node-js.html)
- [2023-09-04] — [Preloading your R packages in webR in an Express JS API](/posts/preloading-your-r-packages-in-webr-in-an-express-js-api.html)
- [2023-07-25] — [The Old Faithful Geyser Data shiny app with webR, Bootstrap & ExpressJS](/posts/old-faithful-express-bootstrap-webr.html)
- [2023-07-04] — [Using webR in an Express JS REST API](/posts/calling-webr-from-expressjs.html)

## aoc {#aoc}

- [2021-12-02] — [Advent of Code 2021-02 with R & JavaScript](/posts/aoc-2021-02.html)
- [2021-12-01] — [Advent of Code 2021-01 with R & JavaScript](/posts/aoc-2021-01.html)
- [2020-12-09] — [Advent of Code 2020-09 with R](/posts/aoc-2020-09.html)
- [2020-12-08] — [Advent of Code 2020-08 with R](/posts/aoc-2020-08.html)
- [2020-12-07] — [Advent of Code 2020-07 with R & Neo4j](/posts/aoc-2020-07.html)
- [2020-12-06] — [Advent of Code 2020-06 with R](/posts/aoc-2020-06.html)
- [2020-12-05] — [Advent of Code 2020-05 with R](/posts/aoc-2020-05.html)
- [2020-12-04] — [Advent of Code 2020-04 with R](/posts/aoc-2020-04.html)
- [2020-12-03] — [Advent of Code 2020-03 with R](/posts/aoc-2020-03.html)
- [2020-12-02] — [Advent of Code 2020-02 with R & JavaScript](/posts/aoc-2020-02.html)
- [2020-12-01] — [Advent of Code 2020-01 with R & JavaScript](/posts/aoc-2020-01.html)
- [2019-12-08] — [Advent of Code 2019-08 with R & JavaScript](/posts/aoc-2019-08.html)
- [2019-12-07] — [Advent of Code 2019-07 with R](/posts/aoc-2019-07.html)
- [2019-12-06] — [Advent of Code 2019-06 with R ](/posts/aoc-2019-06.html)
- [2019-12-05] — [Advent of Code 2019-05 with R & JavaScript](/posts/aoc-2019-05.html)
- [2019-12-04] — [Advent of Code 2019-04 with R & JavaScript](/posts/aoc-2019-04.html)
- [2019-12-03] — [Advent of Code 2019-03 with R & JavaScript](/posts/aoc-2019-03.html)
- [2019-12-02] — [Advent of Code 2019-02 with R & JavaScript](/posts/aoc-2019-02.html)
- [2019-12-01] — [Advent of Code 2019-01 with R & JavaScript](/posts/aoc-2019-01.html)
- [2018-12-04] — [Solving #AdventOfCode day 3 and 4 with R](/posts/advent-code-3-4.html)
- [2018-12-04] — [Solving #AdventOfCode day 5 and 6 with R](/posts/advent-code-5-6.html)
- [2018-12-02] — [Solving #AdventOfCode day 1 and 2 with R](/posts/advent-code-1-2.html)
