---
title: "Using NodeJS and Docker to compare various versions of R"
post_date: 2019-05-14
layout: single
permalink: /node-js-docker-versions-r/
categories: r-blog-en
output: jekyllthat::jekylldown
excerpt_separator: <!--more-->
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path="../assets/img/", eval = TRUE, error =TRUE)
```

Introducting [`ronline`](https://srv.colinfay.me/r-online), a NodeJS app to explore multiple versions of R.

## What is that? 

`ronline` is a web app which you can use to run pieces of R code through various versions of R, and to compare the results between two versions of R. 

## How is it built?

This web app is built on top of three open source elements:

+ [NodeJS](https://nodejs.org/en/), which is used to launch the page, and to communicate between the webpage and the server that launches the Docker calls. 
+ [BootStrap](https://getbootstrap.com/), for the user interface. 
+ [Docker](https://www.docker.com/), and especially the [rocker/r-ver](https://github.com/rocker-org/rocker-versioned) hub, which contains a series of docker containers running current and old version of R. 

## How does it work? 


## Ok, but why?

Well, why not? 

## Can it work with another language?

The core of the app is built on top of NodeJS, and it is used to fetch the content of the editable `div`, turn it into a script, and use it with `docker run`. 

If you feel like it, you could turn this into any other "Compare X" tool, as long as you have containers that can run older versions of the language. 

## Is it secure?

Yes, and no. Yes because it's using temporary containers and temporary file, and the online version is served through https. No because I'm not liable for anything you're putting into this app. Please note that the online version is there primarly for fun and for exploration, so if you want to use it for sensible information processing, you should run this locally, not with the online version. 

## Can it handle large dataset?

No. In order to prevent from blocking the server, each container has a memory limit, so you can't compute large things there. As with the previous point, if you're interested in comparing the computation of large datasets, please install and use a local version of the app. 

## I've found a bug/there is a typo/I've got an idea for improving this

Please [open an issue](https://github.com/ColinFay/ronline/issues) on the GitHub repo. 

## I want to collaborate

Please [open an PR](https://github.com/ColinFay/ronline/pulls) on the GitHub repo, I'll be very happy to receive help on that project.