---
title: "We Run for RLadies"
post_date: 2020-10-05
layout: single
permalink: /we-run-rladies/
categories: r-blog-en
output: jekyllthat::jekylldown
excerpt_separator: <!--more-->
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(fig.path="../assets/img/", eval = TRUE, error =TRUE, comment = "")
```

Hey internet, it's me again!

If you follow this blog, you've seen two weeks ago that we launched a "Run for RLadies" online event, where you could sponsor runners from the [RStats Strava Club](https://www.strava.com/clubs/rstats) (and others), by matching 1$/€ by km run during a run made on the week-end of the 3rf and 4th of October. 

Here is a short summary of how much km each runner run: 

+ Colin F - 21,10 km
+ Jacquie T - 15,02 km
+ Benjamin M - 21,10 km
+ Wal M - 10,01 km
+ Megan B - 30,1 km
+ Theoni P - 7 km
+ Johne P - 9,35 km

__What to do now?__

If you're a sponsor, and even if you're not, you can do a donation to RLadies using the "Donate" button on their [website](https://rladies.org/): it's on the bottom right corner if you're on a computer, and on the very bottom if you're on a mobile 💪. 
If you have a PayPal account, the process takes about 20 seconds ;)

If you don't want/are not able to match the distance run by a specific runner, you can also do a donation of any amount: it can be \$1, \$2, \$10... anything helps!
For example, a Zoom pro account (for 500 users), costs around \$200 a year: that's 20 people donating \$10 (of course, RLadies are free to do what they want with the donation, I just wanted to show that every donation, whatever the amount, can help ;) ). 
