---
title: "Back from useR! 2019"
date: "2019-07-14"
categories: [r-blog-en]
aliases:
  - "/back-from-toulouse/"
---
I’m back from useR\! 2019\!, Toulouse, where I gave one talk and a
workshop. Here are the links to the materials.

## 2019-07-08

### Contributing to the R ecosystem

> useR\! newbie session

A short talk about things you can do as a beginner to contibute to the R
ecosystem.

Slides:
<https://speakerdeck.com/colinfay/contributing-to-the-r-ecosystem>

## 2019-07-09

### Hacking RStudio: Advanced Use of your Favorite IDE

> useR\! Workshop session

*Have you ever wanted to become more productive with RStudio? Then this
workshop is made for you\!*

*You’ve been wandering the web for a while now, reading about all the
things the cool kids do with RStudio: building addins, using project
templates, managing connections, playing around with the rstudioapi
package… All this seems pretty nifty but so far you have never find the
time to sit down and learn how to master these skills. Then, you’ve come
to the right place — this workshop will teach you how to push the
boundaries of your basic RStudio usage, in order to become more
efficient in your day to day usage of RStudio.*

Slides:
<https://speakerdeck.com/colinfay/hacking-rstudio-advanced-use-of-your-favorite-ide>

Repo <https://github.com/ColinFay/user2019workshop>

Example of answers to the exercises
<https://github.com/ColinFay/user2019workshop/tree/master/examples>

```{=html}
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.page.url = "https://colinfay.me/back-from-toulouse/";
  this.page.identifier = "/back-from-toulouse";
};
(function() {
  var d = document, s = d.createElement('script');
  s.src = 'https://http-colinfay-me.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
```
