---
title: "[Keynote] Production is like ultra running: brutal, ungrateful, but worth every step"
date: "2023-05-05"
categories: [r-blog-en]
aliases:
  - "/keynote-shiny-conf-2023/"
---
Hey folks, my keynote at the [shinyconf 2023](https://shinyconf.appsilon.com/) called "Production is like ultra running: brutal, ungrateful, but worth every step" is now online! 

In this talk, I reflect on how ultra running has helped me become a better software engineer, and how building software has helped me learning how to run long distances. 

Giving this talk has been something quite hard for me (probably harder than running 50 miles 😅) — I usually give very technical talks, but for one time decided I should try telling a bit more about me and my story, about why I love running long distances and building software that are used in production.
I hope watching this one will inspire some of you, and feel free to share your thoughts about it with me!

<iframe width="560" height="315" src="https://www.youtube.com/embed/wMbhxTJNrmw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>

Thanks again to the Apsillon team for inviting me to talk, to Vincent and Diane from ThinkR for their support, and to [Maxime](https://www.maximetarcher.com/) for coaching me and pushing me toward being more open about myself.

```{=html}
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.page.url = "https://colinfay.me/keynote-shiny-conf-2023/";
  this.page.identifier = "/keynote-shiny-conf";
};
(function() {
  var d = document, s = d.createElement('script');
  s.src = 'https://http-colinfay-me.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
```
