---
title: "Learning Shiny for Production"
date: "2020-05-31"
categories: [r-blog-en]
aliases:
  - "/learn-shiny-production/"
---
Hey Shiny devs of the world\! I’m leading a training in July about
building a Shiny application for production. It will be a 10 half-day
session, with everything happening remotely, meaning that you can attend
from anywhere in the world 🎉.

During this online workshop, I’ll share a lot of what we know about
building a robust Shiny application that is ready to be sent to
production: `{golem}`, prototyping, modules, reactivity, a little bit of
JavaScript for Shiny, and how and where to deploy your application once
it’s ready.

I’m very excited about this training as it will cover a lot of the
things we’ve been working on for the past months, and will guide you
towards being a better Shiny programmer. And on top of that, we will be
working on our brand new online e-learning platform, which I’ve been
developing since the beginning of 2020 (and I’m sure you will enjoy
it\!).

We still have a couple of tickets left to this session, so if you want
to know more, and register, please visit [Learning Shiny for Production
– Remote
session](https://rtask.thinkr.fr/remote-trainings-and-certification/learning-shiny-online-july/).

See you there\!

```{=html}
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.page.url = "https://colinfay.me/learn-shiny-production/";
  this.page.identifier = "/learn-shiny-production";
};
(function() {
  var d = document, s = d.createElement('script');
  s.src = 'https://http-colinfay-me.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
```
