---
title: "#RStats — languagelayeR : query the languagelayer API with R"
date: "2016-12-12"
categories: [r-blog-en]
aliases:
  - "/rstats-languagelayer-query-the-languagelayer-api-with-r/"
---
## Improve your text analysis with this R package designed to access the languagelayer API.
LanguagelayeR is now on <a href="https://cran.r-project.org/package=languagelayeR">CRAN</a>

### languagelayerR
This package is designed to detect a language from a character string in R by acessing the languagelayer API — <a href="https://languagelayer.com/">https://languagelayer.com/</a>

## Language layer API
This package offers a language detection tool by connecting to the languagelayer API, a JSON interface designed to extract language information from a character string.

## Install languagelayerR
Install this package directly in R : `devtools::install_github"ColinFay/languagelayerR")`
## How languagelayeR works
The version 1.0.0 works with three functions. Which are :

```r 
getLanguage
``` 

Get language information from a character string

```r 
getSupportedLanguage
``` 

Get all current accessible languages on the languagelayer API

```r 
setApiKey
``` 
Set your API key to access the languagelayer API

## First of all
Before any request on the languagelayer, you need to set your API key for your current session. Use the function `setApiKey(apikey = "yourapikey")`.

You can get your api key on your languagelayer <a href="https://languagelayer.com/dashboard">dashboard</a>.

## Examples
### getLanguage
Detect a language from a character string.

```r
getLanguage("I really really love R and that's a good thing, right?")
```

List all the languages available on the languagelayer API.
```r
getSupportedLanguage()
```
### Contact

Questions and feedbacks <a href="mailto:contact@colinfay.me">welcome</a> !
&nbsp;

```{=html}
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.page.url = "https://colinfay.me/rstats-languagelayer-query-the-languagelayer-api-with-r/";
  this.page.identifier = "/rstats-languagelayer-query-the-languagelayer-api-with-r";
};
(function() {
  var d = document, s = d.createElement('script');
  s.src = 'https://http-colinfay-me.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
```
