---
title: "See you at useR! Toulouse"
date: "2019-03-31"
categories: [r-blog-en]
aliases:
  - "/see-you-user-2019"
---
Hey all, just a quick post to give you some details about my workshop at useR! 2019, in Toulouse!



## Hacking RStudio: Advanced Use of your Favorite IDE

### About

Have you ever wanted to become more productive with RStudio? Then this workshop is made for you! 

You've been wandering the web for a while now, reading about all the things the cool kids do with RStudio: 

+ building addins & playing around with the `{rstudioapi}` package, like for example what we do in [`{remedy}`](https://github.com/ThinkR-open/remedy),
+ using project templates, like the one in [`{golem}`](https://github.com/ThinkR-open/golem),
+ managing connections, like the (just for fun) package I wrote called [`{fryingpane}`](https://github.com/ColinFay/fryingpane)... 

All this seems pretty nifty but so far you have never find the time to sit down and learn how to master these skills. Then, you've come to the right place — my useR workshop will teach you how to push the boundaries of your basic RStudio usage, in order to become more efficient in your day to day usage of RStudio. 

### Target audience 

We expect people to be familiar with RStudio, and have a little knowledge about programming with R. Knowing how to build a package will be better, but is not mandatory. 

### Instruction

Please come with a recent version of RStudio installed.

## Sign up for useR

useR! 2019 will be hold from the 9th to the 12th of July, in Toulouse.

Early birds close soon (May 7th), so hurry ;) 

[http://www.user2019.fr/registration/](http://www.user2019.fr/registration/)

```{=html}
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.page.url = "https://colinfay.me/see-you-user-2019";
  this.page.identifier = "/see-you-user";
};
(function() {
  var d = document, s = d.createElement('script');
  s.src = 'https://http-colinfay-me.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the comments powered by Disqus.</noscript>
```
